### ISSUE TITLE
抽水设置中，矿池地址选择蚂蚁的情况下，抽水比例大于0%，会出现矿机连接后自动断开的情况

### ISSUE THREAD

**Issue by jinglikeblue** [Allminer/minerProxy#1]
# 抽水设置中，矿池地址选择蚂蚁的情况下，抽水比例大于0%，会出现矿机连接后自动断开的情况
测试的协议：
- ETC
- RVN
都会出现Title所示问题

**Comment by Allminer** [comment]
@jinglikeblue 更新到新版试试，如果还有问题，请贴一下端口日志
